let quotes = ["The only way to do great work is to love what you do. - Steve Jobs", 
"Be yourself; everyone else is already taken. - Oscar Wilde", 
"In the middle of difficulty lies opportunity. - Albert Einstein", 
"The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt", 
"Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill", 
"The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela", 
"Believe you can and you're halfway there. - Theodore Roosevelt", 
"The best way to predict the future is to create it. - Peter Drucker", 
"The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt", 
"The purpose of our lives is to be happy. - Dalai Lama", 
"The greatest wealth is health. - Virgil", 
"Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer", 
"You miss 100% of the shots you don't take. - Wayne Gretzky", 
"Do not wait for the right moment. Create it. - George Bernard Shaw", 
"Life is either a daring adventure or nothing at all. - Helen Keller", 
"The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke", 
"The best revenge is massive success. - Frank Sinatra", 
"Don't watch the clock; do what it does. Keep going. - Sam Levenson", 
"The way to get started is to quit talking and begin doing. - Walt Disney", 
"Happiness is not something rea -made. It comes from your own actions.  - Dalai Lamad,y",
"The only person you should try to be better than is the person you were yesterday. - Unknown",
"Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau", 
"Dream big and dare to fail. - Norman Vaughan", 
"You become what you believe. - Oprah Winfrey", 
"The harder I work, the luckier I get. - Samuel Goldwyn", 
"I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean", 
"Everything you can imagine is real. - Pablo Picasso", 
"The only true wisdom is in knowing you know nothing. - Socrates", 
"If you want to lift yourself up, lift up someone else. - Booker T. Washington", 
"Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll", 
"The secret of getting ahead is getting started. - Mark Twain", 
"It does not matter how slowly you go as long as you do not stop. - Confucius", 
"The only way to do great things is to love what you do. - Steve Jobs", 
"You are never too old to set another goal or to dream a new dream. - C.S. Lewis", 
"The biggest risk is not taking any risk. - Mark Zuckerberg", 
"Don't be afraid to give up the good to go for the great. - John D. Rockefeller", 
"I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison", 
"The true sign of intelligence is not knowledge but imagination. - Albert Einstein", 
"It is during our darkest moments that we must focus to see the light. - Aristotle", 
"You must be the change you wish to see in the world. - Mahatma Gandhi", 
"The only way to have a friend is to be one. - Ralph Waldo Emerson", 
"The greatest pleasure in life is doing what people say you cannot do. - Walter Bagehot", 
"Success is not in what you have, but who you are. - Bo Bennett", 
"A journey of a thousand miles begins with a single step. - Lao Tzu", 
"The best revenge is living well. - Jerry Seinfeld", 
"The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it. - Michelangelo", 
"It's not the years in your life that count. It's the life in your years. - Abraham Lincoln", 
"The biggest communication problem is we do not listen to understand. We listen to reply. - Stephen R. Covey", 
"If you want to fly, you have to give up the things that weigh you down. - Toni Morrison", 
"Opportunities don't happen. You create them. - Chris Grosser"]

let quote = document.getElementById('quote');
let btn = document.getElementById('btn');

btn.addEventListener('click', () => {
    let random = quotes[Math.floor(Math.random() * quotes.length)];
    quote.innerHTML = random;
});